---
title: Real World Implementation Guides

roles:
  - Investigator
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

learning_objectives2:
  - Review existing FHIR IGs that may be relevant to researchers.

reading_time: true
---

FHIR Implementation Guides (IGs) provide a mechanism for use-case specific customization of the FHIR specification.

::: {.callout-tip appearance="minimal"}
Please see [the "Customizing FHIR" section in FHIR from 1,000 Feet](fhir-from-1000-ft.qmd#customizing-fhir) for a high-level overview of FHIR IGs and profiling. [Reading IGs](data-modeling-reading-igs.qmd) provides additional details.
:::

Examples of FHIR IGs that may be of interest to researchers are listed below. This is not meant to be an exhaustive list, but rather to demonstrate the scope of the IGs that have been published and identify some of the key IGs (identified with ⭐️) to be aware of in the FHIR ecosystem. A [full list of IGs published through HL7® is available here](http://www.fhir.org/guides/registry/), and additional IGs may be published outside of HL7.

-   [**Adverse Events for Clinical Research**](https://build.fhir.org/ig/HL7/fhir-ae-research-ig/), which provides an approach for representing adverse events in clinical research with FHIR. (Note that as of April 2023, this IG has not gone through the FHIR balloting process yet. The provided link is to the "live build" of the IG.)

-   [**Bulk Data**](https://hl7.org/fhir/uv/bulkdata/)⭐️, which provides a mechanism for extracting population-scale data from FHIR servers. [See here for more information](smart-on-fhir-intro.qmd#bulk-data-access).

-   [**Common Data Models Harmonization**](http://hl7.org/fhir/us/cdmh/), which focuses "on mapping and translating observational data extracted for Patient Centered Outcome Research (PCOR) and other purposes into FHIR format" and supports PCORNet, i2b2, i2b2, and Sentinel data models.

-   [**Electronic Case Reporting**](http://hl7.org/fhir/us/ecr/), which supports public health electronic case reporting.

-   [**GA4GH Phenopackets**](http://phenopackets.org/core-ig/ig/branch/master/index.html), which "intends to support global exchange of computable case-level phenotypic information for all types of disease diagnosis and research." (Note that this is an example of an IG published outside of HL7.)

-   [**Genomics Reporting**](http://hl7.org/fhir/uv/genomics-reporting/), which provides FHIR versions of common data structures involving genomics data like [genotypes](http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition-genotype.html) and [variants](http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition-variant.html).

-   [**International Patient Summary**](http://hl7.org/fhir/uv/ips/), which "is designed for supporting the use case scenario for 'unplanned, cross border care', but it is not limited to it. It is intended to be international, i.e., to provide generic solutions for global application beyond a particular region or country."

-   [**mCODE**](https://hl7.org/fhir/us/mcode/), which provides "a core set of structured data elements for oncology electronic health records (EHRs)."

-   [**Quality Improvement Core**](http://hl7.org/fhir/us/qicore/), which supports interoperable clinical quality measures and clinical decision support.

-   [**Retrieval of Real World Data for Clinical Research**](https://build.fhir.org/ig/HL7/vulcan-rwd/), which supports the use of real world data for research purposes. (Note this link is to a a "live build" of the IG; as of April 2023 this IG has been balloted but not published through HL7. Once published, the IG will be accessible at <https://hl7.org/fhir/uv/vulcan-rwd>.)

-   [**Situational Awareness for Novel Epidemic Response**](http://hl7.org/fhir/uv/saner/), which "enables transmission of high level situational awareness information from inpatient facilities to centralized data repositories to support the treatment of novel influenza-like illness."

-   [**US Core**](https://www.hl7.org/fhir/us/core/)⭐️, which is the FHIR IG that implements USCDI ([more information here](fhir-from-1000-ft.qmd#example-customizing-patient-in-us-core)). This IG is highly relevant for researchers in the US because EHRs typically implement US Core as part of their FHIR implementations. Conversely, data elements that are not covered by US Core may not be consistently implemented in US EHR FHIR implementations.\
    \
    Many US-centric IGs use US Core as a starting point, so you may encounter US Core profiles when viewing other IGs. If you author a FHIR IG for US implementation, it may be beneficial to also follow this approach.