---
title: Emerging Innovations

roles:
  - Investigator
  - Research Leaders
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

reading_time: true
---

## Introduction

The core technologies that underpin health data interoperability—FHIR, SMART on FHIR, CDS Hooks, and Bulk FHIR—play crucial roles in enabling standardized, secure, and efficient health data exchange. However, the landscape of health data interoperability is continuously evolving, influenced by recent regulatory changes and technological advancements. Keeping abreast of these developments is crucial for researchers, as they shape the ways we can access, use, and exchange health data for research.

## Recent Regulatory Developments and Their Impact

### Overview of Key Regulations

The following summarizes key regulations and their implications for research.

[**21st Century Cures Act**](https://www.healthit.gov/topic/oncs-cures-act-final-rule):

-   **Provisions on Data Blocking, Interoperability, and Patient Access:** The 21st Century Cures Act significantly enhances health data interoperability by mandating the use of FHIR as a standard for Health IT Certification. It ensures that electronic health information (EHI) can be securely and easily exchanged across EHR platforms and requires the inclusion of core health data elements defined by the [United States Core Data for Interoperability (USCDI)](https://www.healthit.gov/isp/united-states-core-data-interoperability-uscdi). This sets the foundation for making standardized, computable data elements more readily available for researchers. Additionally, the Act's provisions against information blocking facilitate patient access to their health data, opening new opportunities for integrating patient-reported data into research.

-   **Mandating Standardized APIs:** By requiring health IT systems to adopt standardized APIs like FHIR, the act enables seamless and scalable data exchange. This support extends to a variety of research activities, from observational studies to real-time data analysis, by ensuring data is accessible in a consistent format across different health systems.

[**HTI-1 Final Rule**](https://www.healthit.gov/topic/laws-regulation-and-policy/health-data-technology-and-interoperability-certification-program):

-   **Driving Data Standardization:** The Health IT Interoperability (HTI-1) final rule updates health IT certification criteria, increasing the availability of core health data elements for exchange via FHIR. This ensures researchers can obtain more reliable and consistent data from certified EHR systems, enhancing the quality of data used in research. It also supports the adoption of updates to standardized API requirements.

-   **Decision Support Interventions and Predictive Models:** HTI-1 extends clinical decision support certification criteria into the realm of artificial intelligence. The Decision Support Intervention (DSI) criteria promote transparency of the algorithms, data, and processes used in developing predictive models for DSI, ensuring that clinical decision-making tools are evidence-based and transparent.

[**TEFCA (Trusted Exchange Framework and Common Agreement)**](https://www.healthit.gov/topic/interoperability/policy/trusted-exchange-framework-and-common-agreement-tefca):

-   **Creating a Standardized National Framework:** TEFCA aims to establish a single, standardized framework for nationwide health data exchange, potentially providing researchers with easier access to data across various health networks. This could streamline the process of acquiring real-world health data, enhancing the ability to conduct large-scale studies and fostering collaboration across institutions.

-   **Improving Data Accessibility for Researchers:** With TEFCA’s framework, researchers could gain access to a more extensive pool of health data, making it easier to identify patient cohorts, track outcomes, and conduct longitudinal studies.

#### Opportunities for Research

-   **Comprehensive Access to Real-World Data:** These regulations make it possible for researchers to access more comprehensive, real-world health data, leading to a deeper understanding of patient populations and health outcomes. The 21st Century Cures Act and HTI-1 have laid a new foundation for health interoperability, with standardized core electronic health data becoming more widely available. These regulations further support transparent development of clinical decision support technologies and artificial intelligence algorithms in health applications. The act's information blocking provisions empower patients to access their health data, potentially opening new doors for patient-facilitated research.

-   **Facilitating Collaboration:** Standardized data formats and exchange protocols offer new opportunities for multi-site and cross-institutional research collaborations, allowing for larger sample sizes and more diverse data sets.

#### Challenges and Gaps

-   **Ensuring Data Privacy:** With increased data sharing, maintaining patient privacy and complying with regulations like HIPAA is a critical concern. Researchers must navigate the complexities of de-identifying data and ensuring secure access.

-   **Overcoming Technical Barriers:** Aligning diverse data-sharing practices and integrating various EHR systems can be technically challenging. Researchers may also encounter varying interpretations of regulatory requirements, which can affect data exchange.

## Industry Innovations and Their Impact

### AI and Machine Learning

Artificial Intelligence (AI) and Machine Learning (ML) are revolutionizing healthcare by enabling the analysis of vast datasets to extract meaningful patterns, enhance diagnostics, and predict health outcomes. These technologies have found applications across various medical fields, including radiology, cardiology, oncology, and ophthalmology—significantly improving patient care and operational efficiency.

For instance, in radiology, AI algorithms assist in detecting anomalies in medical images, aiding in the early diagnosis of diseases (@Hosny_Parmar_2018). In oncology, ML models predict cancer progression and patient responses to treatments, facilitating personalized medicine (@Shimizu_Nakayama_2020). In cardiology, AI tools analyze electronic health records (EHRs) to predict cardiovascular events, improving preventive care strategies (@Krittanawong_Johnson_2019). In ophthalmology, AI systems have been developed to detect retinal diseases such as diabetic retinopathy and glaucoma from fundus photographs with high accuracy, enabling early intervention and management (@Li_He_2018).

The effectiveness of AI and ML in healthcare hinges on the availability of large volumes of high-quality, standardized data. In this context, the FHIR standard emerges as a crucial enabler. AI and ML algorithms require data that is not only vast in quantity but also consistent in structure. The use of standardized data formats like FHIR ensures that data from various sources can be integrated seamlessly. This standardization is critical for training AI models effectively, as it reduces the variability and potential errors that can arise from disparate data formats.

FHIR enables the integration of diverse data types, such as electronic health records (EHRs), imaging data, and patient-reported outcomes. By providing a common framework, FHIR facilitates interoperability between different healthcare systems and devices. This interoperability is essential for aggregating the large datasets needed for AI and ML applications.

Furthermore, FHIR enhances data interoperability by allowing for real-time data exchange. This capability is particularly beneficial in AI-driven Clinical Decision Support (CDS), where patient data needs to be transmitted quickly and securely to trigger the AI model or provide data for inference.

### Cloud Computing and Big Data Analytics

The rapid increase in healthcare data, including electronic health records (EHRs) and information from wearable devices, has made traditional on-premises data storage less practical. Cloud platforms offer scalable and flexible infrastructures that can handle vast amounts of data, providing healthcare organizations with the ability to store, manage, and analyze information more efficiently.

Cloud services enable the aggregation of diverse data types into a centralized repository, facilitating seamless data sharing and collaboration among healthcare providers, researchers, and patients. By leveraging FHIR APIs and clinical terminologies, cloud-based solutions reduce integration challenges that stem from data from different sources and systems. This interoperability is crucial for creating comprehensive patient records and supporting coordinated care efforts across multiple providers and healthcare systems.

Cloud platforms also support advanced big data analytics by providing the computational power necessary to process large datasets. Healthcare organizations can utilize cloud-based analytics tools to perform real-time data analysis, predictive modeling, and machine learning applications. For instance, analyzing population health trends or predicting patient outcomes becomes more feasible when computational resources can scale according to demand. For infrequent or variable workflows, this scalability not only enhances operational efficiency but also reduces the costs associated with maintaining extensive on-premises IT infrastructures. However, on-premises solutions may be more cost-effective for high-volume, consistent workloads in the long term.

Cloud computing promotes innovation by enabling researchers to access and analyze data on-demand from anywhere, unconstrained by local infrastructure. This facilitates streamlined collaboration as data can be securely shared and accessed globally. The adoption of standardized data formats like FHIR further enhances collaboration, helping to ensure consistency and reliability in data analysis across various research domains.

A notable example of a cloud-based clinical data initiative is the [**National COVID Cohort Collaborative (N3C)**](https://covid.cd2h.org/) (@Haendel_Chute_2021). N3C is a nationwide effort that aggregates and harmonizes EHR data from numerous healthcare institutions into a centralized, secure cloud environment specifically for COVID-19 research. While not currently FHIR-based, N3C recognizes the potential of FHIR for future development, as it may offer enhanced interoperability and alignment with emerging health data standards. The N3C platform allows for advanced big data analytics, facilitating studies on disease progression, treatment efficacy, and long-term outcomes related to COVID-19, with the goal of improving patient care and public health responses to the pandemic.

#### Benefits

The integration of cloud computing and big data analytics in healthcare offers numerous advantages:

-   Support for Large-Scale Research Studies: Cloud platforms enable the collection and analysis of extensive datasets from diverse sources. Researchers can conduct large-scale studies that were previously impractical due to data storage and processing limitations. This capability accelerates medical research and the development of new treatments and interventions.

-   Real-Time Data Analysis: Cloud computing facilitates the rapid processing of incoming data, allowing healthcare providers to analyze information as it is generated. This real-time capability supports timely clinical decision-making, enhances patient monitoring, and improves the responsiveness of healthcare services.

#### Challenges

Despite these benefits, several challenges need to be addressed:

-   Data Security: Protecting sensitive health information in the cloud is a critical concern. Ensuring compliance with regulations like [the Health Insurance Portability and Accountability Act (HIPAA)](https://www.hhs.gov/hipaa/index.html) and [the Federal Trade Commission (FTC) Health Breach Notification Rule](https://www.ftc.gov/legal-library/browse/rules/health-breach-notification-rule) requires robust security measures, including encryption, access controls, and regular security assessments. Any breaches can have severe legal and ethical implications, including substantial fines and damage to an organization's reputation.

-   Integration Complexity: Migrating existing systems to cloud platforms can be complex. Compatibility issues arise, especially with legacy systems or non-standardized data formats. While adopting interoperability standards like FHIR is essential, it may require considerable effort to implement effectively across all systems involved.

-   Need for Technical Expertise: Implementing and maintaining cloud-based solutions necessitates specialized knowledge. Healthcare organizations may face challenges in recruiting or training staff with expertise in cloud technologies, data analytics, and cybersecurity. Investing in staff training or partnering with experienced vendors can help address this gap but may increase operational costs.

When implemented effectively, and by leveraging standards like FHIR, these technologies have the potential to significantly enhance patient care, advance medical research, and improve the overall efficiency of healthcare services.

## Conclusion

The maturation and widespread adoption of FHIR, along with complementary technologies like SMART on FHIR, CDS Hooks, and Bulk FHIR, are fundamentally transforming the landscape of health research. These innovations are not only improving how we access and share data but also opening up new avenues for research and discovery:

-   **Improved Data Access and Sharing:** The 21st Century Cures Act, HTI-1, and frameworks like TEFCA are creating a more secure and standardized environment for accessing electronic health records (EHRs) and patient data. This enables seamless multi-site studies and fosters cross-organizational collaborations, accelerating the pace of research.

-   **Enhanced Data Quality and Standardization:** FHIR's standardization capabilities are significantly improving data consistency and reliability. Researchers can now aggregate data across diverse systems and sources more effectively, enhancing the integrity and outcomes of their research.

-   **Real-Time Data Availability and Insights:** The ability to access and analyze real-time data through FHIR paves the way for more dynamic and responsive clinical trials and observational studies. This enhanced data accessibility facilitates longitudinal studies, offering deeper insights into patient health trajectories.

-   **New Opportunities for Research Recruitment and Engagement:** Interoperable data and AI-driven tools are streamlining the identification and recruitment of study participants. By personalizing recruitment strategies, researchers can engage participants more effectively and improve study outcomes.

### Looking Ahead: Navigating Future Opportunities and Challenges

As we look to the future, researchers should remain vigilant about emerging trends and potential challenges. While these technological advancements offer significant benefits, they also introduce complexities, such as ensuring data privacy and managing the technical integration of diverse health data systems. The ongoing evolution of regulations and standards will require researchers to be adaptable and proactive in leveraging new opportunities while maintaining compliance and ethical standards.