server:
  port: 8080

management:
  # Configure endpoints /actuator/health, /actuator/info, /actuator/prometheus, /actuator/metrics.
  # For security purposes, only /actuator/health is enabled by default.
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health' # any combination of 'info,health,prometheus,metrics' or '*' for all
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - readinessState
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: false
    baselineOnMigrate: true
    fail-on-missing-locations: false
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      hibernate.search.enabled: false

hapi:
  fhir:
    fhir_version: R4

    cr: # Clinical Reasoning
      enabled: false
      caregaps:
        reporter: "default"
        section_author: "default"
      cql:
        use_embedded_libraries: true
        compiler:
          error_level: Info
          signature_level: All
          enable_annotations: true
          enable_locators: true
          enable_results_type: true
          enable_detailed_errors: true
        runtime:
          debug_logging_enabled: false
        terminology:
          valueset_preexpansion_mode: REQUIRE # USE_IF_PRESENT, REQUIRE, IGNORE
          valueset_expansion_mode: PERFORM_NAIVE_EXPANSION # AUTO, USE_EXPANSION_OPERATION, PERFORM_NAIVE_EXPANSION
          valueset_membership_mode: USE_EXPANSION # AUTO, USE_VALIDATE_CODE_OPERATION, USE_EXPANSION
          code_lookup_mode: USE_VALIDATE_CODE_OPERATION # AUTO, USE_VALIDATE_CODE_OPERATION, USE_CODESYSTEM_URL
        data:
          search_parameter_mode: USE_SEARCH_PARAMETERS # AUTO, USE_SEARCH_PARAMETERS, FILTER_IN_MEMORY
          terminology_parameter_mode: FILTER_IN_MEMORY #  AUTO, USE_VALUE_SET_URL, USE_INLINE_CODES, FILTER_IN_MEMORY
          profile_mode: DECLARED # ENFORCED, DECLARED, OPTIONAL, TRUST, OFF

    cdshooks:
      enabled: false
      clientIdHeaderName: client_id

    openapi_enabled: true

    ig_runtime_upload_enabled: false

    custom_content_path: ./custom
    app_content_path: ./configs/app

    advanced_lucene_indexing: false

    bulk_export_enabled: true
    bulk_import_enabled: true

    narrative_enabled: false
    mdm_enabled: false
    mdm_rules_json_location: "mdm-rules.json"

    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*

    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'

    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200

    search_prefetch_thresholds: 13,503,2003,-1

    tester:
      home:
        name: Local
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4

    inline_resource_storage_below_size: 4000
